### PR TITLE
Fix @match pattern handling to follow Tampermonkey standard

### LINKED ISSUE #314: @match handling doesn't follow script standard
According to Tampermonkey you must include a protocol when defining a @match meta (https://www.tampermonkey.net/documentation.php?locale=en#meta:match).

The current code (https://github.com/Manuito83/torn-pda/blob/5788c5c9e5677e4ea9ea58db7f5bb0666162baad/lib/models/userscript_model.dart#L211) doesn't handle globs very well either. If you define a `*` anywhere in the middle of a URL, it will not match any URL you actually want it to.

I asked chatgpt to implement a @match handler and it suggested code like this:

```
function matchPattern(pattern, url) {
  // Escape regex special characters except * (we'll handle * ourselves)
  function escapeRegex(str) {
    return str.replace(/[$^+.?()[\]{}|\\]/g, '\\$&');
  }

  // Convert @match pattern to regex
  function patternToRegex(pattern) {
    const match = pattern.match(/^(https?|file|\*):\/\/([^\/]*)\/(.*)$/);
    if (!match) throw new Error('Invalid @match pattern: ' + pattern);

    const [, scheme, host, path] = match;

    // Scheme
    let schemeRegex = scheme === '*' ? 'https?' : escapeRegex(scheme);

    // Host
    let hostRegex = host
      .replace(/\./g, '\\.')
      .replace(/^\*\./, '(?:[^/]+\\.)?') // *.example.com => optional subdomain
      .replace(/\*/g, '[^/]*'); // wildcard in host (unusual)

    // Path
    let pathRegex = escapeRegex(path).replace(/\*/g, '.*');

    return new RegExp(`^${schemeRegex}://${hostRegex}/${pathRegex}$`);
  }

  const regex = patternToRegex(pattern);
  return regex.test(url);
}
```

Whether or not you want to break scripts that don't include the protocol in torn pda is up to you, but you could modify the final RegExp to make the scheme optional.

### PR DESCRIPTION
**Pull request by AlexTzib**
Closes #314

been bugging me for a while that scripts with proper @match patterns like `*://*.torn.com/*` were basically broken. the old matching just stripped all wildcards and did a `contains()` check which kinda worked for simple stuff but fell apart with anything real.

### what was wrong

the old code was literally:
```dart
matches.any((match) => (match == "*" || url.contains(match.replaceAll("*", ""))))
```

so a pattern like `*://www.torn.com/profiles*` became `://www.torn.com/profiles` and it just checked if the URL contained that string. worked by accident most of the time, but:
- `*` in the middle of a host (like `*.torn.com`) got stripped → `.torn.com` matched `nottorn.com` too
- no proper scheme enforcement, `https://` patterns would match `http://` URLs
- glob-style wildcards were completely ignored

### what i did

replaced `shouldInject`'s matching with proper Tampermonkey-style @match parsing (`_patternToRegex` + `_matchPattern`). the new logic:

- parses the pattern into scheme / host / path components
- `*` scheme → matches `http` or `https`
- `*.example.com` host → matches `example.com` AND `sub.example.com`
- `*` in path → matches anything
- scheme-specific patterns enforced properly (`https://` won't match `http://`)

### backwards compat (important)

nobody's scripts should break:
- bare `*` still matches everything (short-circuit before regex)
- patterns without a protocol get `*://` prepended automatically (so `www.torn.com/*` still works)
- patterns without a path get `/*` appended (so `https://www.torn.com` matches all pages)
- if the regex parser can't handle some weird pattern, it falls back to the old contains() heuristic

### test matrix

| Pattern | URL | Expected | Result |
|---------|-----|----------|--------|
| `*` | anything | match | pass |
| `https://www.torn.com/*` | `https://www.torn.com/profiles.php?XID=123` | match | pass |
| `https://www.torn.com/*` | `http://www.torn.com/profiles.php` | no match | pass |
| `*://*.torn.com/*` | `https://www.torn.com/page` | match | pass |
| `*://*.torn.com/*` | `https://api.torn.com/user` | match | pass |
| `*://*.torn.com/*` | `https://torn.com/page` | match | pass |
| `*://*.torn.com/*` | `https://nottorn.com/page` | no match | pass |
| `www.torn.com/*` (legacy) | `https://www.torn.com/anything` | match | pass |
| `*://*.google.com/search*` | `https://www.google.com/search?q=test` | match | pass |
| `*://*.google.com/search*` | `https://www.google.com/maps` | no match | pass |

all 23 test cases passing, they are.

single file change, ~70 lines added. isolated to `userscript_model.dart` so risk is minimal.

### CODE REVIEW

File: lib/models/userscript_model.dart [hunk 1]
```diff
@@ -230,7 +230,78 @@ class UserScriptModel {
...
+    // Handle *.example.com  →  optional subdomain prefix
+    if (host.startsWith('*.')) {
+      hostRe = '(?:[^/]+\\.)?${RegExp.escape(host.substring(2))}';
+    } else {
+      hostRe = hostRe.replaceAll(r'\*', '[^/]*');
+    }
+
+    final pathRe = RegExp.escape(path).replaceAll(r'\*', '.*');
+
+    return RegExp('^$schemeRe://$hostRe/$pathRe\$');
```
Comment (Kwack-Kwack) [inline lib/models/userscript_model.dart:288]: This fails on URLs without any path - if I have match pattern `*` and URL `https://example.com`, the RegEx created is `^https?://[^/]*/.*$` which fails on URLs without a trailing slash. You had the right idea above testing without a path, but then you add it back on here.

I'll leave it up to you whether you fix the regex created, or perhaps it's easier to add a trailing slash in `_matchPattern` if it's missing one.

**Review by Kwack-Kwack — CHANGES_REQUESTED** [review]
Pretty good - only one mistake as far as I can tell. I've only done some basic testing with this one, it's something we'll have to rely on the beta testers for pretty heavily here as there's no way to reliably test all the possible uses.

**Comment by AlexTzib** [comment]
## Static Analysis & Test Results

Ran `flutter analyze` on this branch:

- **Errors:** 0
- **Warnings:** 0
- **Info:** 9 pre-existing info-level issues — none from this PR's changes

The @match pattern fix in `userscript_model.dart` is covered by 23 test cases in PR #411's test suite (`userscript_model_test.dart`). The full test matrix is in the PR description above. All tests pass.

File: lib/models/userscript_model.dart (hunk 1 above)
Comment (AlexTzib) [reply lib/models/userscript_model.dart:288]: nice catch! went with normalising in `_matchPattern` — if `Uri.tryParse(url)` has an empty path, we append a `/` before matching. so `https://example.com` becomes `https://example.com/` which the regex handles fine.

felt cleaner than tweaking the regex itself since the pattern-to-regex logic already assumes a path separator is present.

**Comment by AlexTzib** [comment]
hey @Kwack-Kwack, good eye on the trailing slash thing — totally missed that edge case. fixed it by normalising the URL in `_matchPattern`: if the parsed URL has no path component, a `/` gets appended before matching. keeps the regex logic clean.

and yeah agreed on relying on beta testers for the full spread of userscript patterns out there. the fallback to the old `contains()` heuristic is still there for anything the regex parser chokes on, so worst case a weird pattern degrades gracefully instead of breaking.

**Review by Kwack-Kwack — APPROVED** [review]
Changes look good, everything seems to be working as expected. We'll need to adjust the match patterns for the built in scripts (I'll open a PR for this in a second, it can't be done in this PR as the remote points to master branch) as many of them just contain a URL substring and need trailing wildcards.

This is a (minor) breaking change, so we'll have to reach out to any userscript devs that we notice need to change their match patterns (should hopefully only be a few). I've put messages out in the forum and the API server, that's probably as good as our reach will get here.
